import { afterEach, expect, it, vi } from 'vitest';
import { settled } from '@gyral/core';
import { Controls } from '../../src/app/controls.ts';
import { provideSession } from '../../src/app/drivers.ts';
import { Session } from '../../src/runtime/session.ts';
import { ChamberElement } from '../../src/app/chamber-element.ts';

const cleanup: (() => void)[] = [];
afterEach(() => { document.body.replaceChildren(); cleanup.splice(0).forEach(stop => stop()); });
it('connects Gyral buttons to the real session and releases them on removal', async () => {
  const root = document.createElement('div'), session = new Session(4);
  document.body.append(root); cleanup.push(provideSession(root, session));
  const element = new Controls(); root.append(element); await settled();
  root.querySelector('summary')?.click();
  const button = (text: string) => [...root.querySelectorAll('button')].find(b => b.textContent?.includes(text))!;
  button('Slow pace').click(); await settled(); expect(session.snapshot.game.slow).toBe(true);
  button('Start game').click(); await settled(); expect(root.querySelector('[data-phase]')?.getAttribute('data-phase')).toBe('playing');
  expect(button('Slow pace').disabled).toBe(true);
  button('Vertical wall').click(); await settled(); expect(session.snapshot.axis).toBe('horizontal');
  button('Pause game').click(); await settled(); expect(session.snapshot.game.phase).toBe('paused');
  element.remove(); session.dispatch({ type: 'restart' }); await settled(); expect(root.textContent).toBe('');
});
it('renders a real WebGL chamber and supports keyboard aiming, building, and disconnect', () => {
  const host = document.createElement('div'); host.style.cssText = 'width:700px;height:500px'; document.body.append(host);
  const session = new Session(6), chamber = new ChamberElement(); chamber.session = session; host.append(chamber);
  chamber.style.cssText = 'display:block;width:100%;height:100%';
  expect(chamber.querySelector('canvas')).not.toBeNull(); expect(chamber.dataset.ready).toBe('true');
  session.dispatch({ type: 'restart' }); chamber.focus();
  chamber.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true }));
  chamber.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  expect(session.snapshot.game.cut?.x).toBe(15);
  chamber.dispatchEvent(new KeyboardEvent('keydown', { key: 'r', bubbles: true })); expect(session.snapshot.axis).toBe('horizontal');
  chamber.remove(); expect(chamber.querySelector('canvas')).toBeNull(); expect(chamber.dataset.ready).toBeUndefined();
  session.close();
});
it('preserves the run and blocks resume through automatic GPU restoration', async () => {
  const host = document.createElement('div'); host.style.cssText = 'width:700px;height:500px'; document.body.append(host);
  const session = new Session(8), chamber = new ChamberElement(); chamber.session = session; host.append(chamber);
  chamber.style.cssText = 'display:block;width:100%;height:100%';
  session.dispatch({ type: 'restart' }); session.frame(0.05);
  session.dispatch({ type: 'place', x: 14, y: 10, axis: 'vertical' });
  const before = session.snapshot.game;
  const canvas = chamber.querySelector('canvas')!;
  const gl = canvas.getContext('webgl2')!;
  const extension = gl.getExtension('WEBGL_lose_context'); expect(extension).not.toBeNull();
  extension!.loseContext();
  await vi.waitFor(() => expect(chamber.dataset.graphics).toBe('lost'));
  expect(session.snapshot.game.phase).toBe('paused'); expect(session.snapshot.blocked).toBeTruthy();
  const paused = session.snapshot.game;
  session.frame(5); session.dispatch({ type: 'pause' }); session.dispatch({ type: 'restart' });
  expect(session.snapshot.game).toBe(paused);
  extension!.restoreContext();
  await vi.waitFor(() => expect(chamber.dataset.graphics).toBe('ready'));
  expect(chamber.querySelector('canvas')).not.toBe(canvas); expect(session.snapshot.blocked).toBeNull();
  expect(session.snapshot.game.tick).toBe(before.tick); expect(session.snapshot.game.balls).toEqual(before.balls);
  expect(session.snapshot.game.cut).toEqual(before.cut); expect(session.snapshot.game.phase).toBe('paused');
  session.dispatch({ type: 'pause' }); session.frame(0.05); expect(session.snapshot.game.tick).toBeGreaterThan(before.tick);
  chamber.remove(); session.close();
});
it('preserves the run and blocks resume until manual GPU recovery', async () => {
  const host = document.createElement('div'); host.style.cssText = 'width:700px;height:500px'; document.body.append(host);
  const session = new Session(10), chamber = new ChamberElement(); chamber.session = session; host.append(chamber);
  chamber.style.cssText = 'display:block;width:100%;height:100%';
  session.dispatch({ type: 'restart' }); session.frame(0.05);
  session.dispatch({ type: 'place', x: 14, y: 10, axis: 'vertical' });
  const before = session.snapshot.game, canvas = chamber.querySelector('canvas')!;
  const extension = canvas.getContext('webgl2')!.getExtension('WEBGL_lose_context'); expect(extension).not.toBeNull();
  extension!.loseContext();
  await vi.waitFor(() => expect(chamber.dataset.graphics).toBe('lost'));
  expect(session.snapshot.game.phase).toBe('paused'); expect(session.snapshot.blocked).toBeTruthy();
  const interrupted = session.snapshot.game;
  session.frame(5); session.dispatch({ type: 'pause' }); session.dispatch({ type: 'restart' });
  expect(session.snapshot.game).toBe(interrupted);
  // A browser need not restore automatically: the player can recreate it directly.
  chamber.querySelector<HTMLButtonElement>('.retry-graphics')!.click();
  expect(chamber.dataset.graphics).toBe('ready'); expect(chamber.querySelector('canvas')).not.toBe(canvas);
  expect(session.snapshot.game).toBe(interrupted); expect(session.snapshot.blocked).toBeNull();
  expect(session.snapshot.game.tick).toBe(before.tick); expect(session.snapshot.game.balls).toEqual(before.balls);
  expect(session.snapshot.game.cut).toEqual(before.cut); expect(session.snapshot.game.phase).toBe('paused');
  session.dispatch({ type: 'pause' }); session.frame(0.05); expect(session.snapshot.game.tick).toBeGreaterThan(before.tick);
  chamber.remove(); session.close();
});
it('ignores cancelled touch gestures rather than building from a stale touch', () => {
  const host = document.createElement('div'); host.style.cssText = 'width:700px;height:500px'; document.body.append(host);
  const session = new Session(9), chamber = new ChamberElement(); chamber.session = session; host.append(chamber);
  chamber.style.cssText = 'display:block;width:100%;height:100%'; session.dispatch({ type: 'restart' });
  chamber.dispatchEvent(new PointerEvent('pointerdown', { pointerType: 'touch', clientX: 350, clientY: 250 }));
  chamber.dispatchEvent(new PointerEvent('pointercancel', { pointerType: 'touch' }));
  chamber.dispatchEvent(new PointerEvent('pointerup', { pointerType: 'touch', clientX: 350, clientY: 250, button: 0 }));
  expect(session.snapshot.game.cut).toBeNull(); chamber.remove(); session.close();
});
